# Generated by Django 2.1.5 on 2019-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190301_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='main-entree', unique=True),
            preserve_default=False,
        ),
    ]
